#!/usr/bin/env node
/**
 * add-note.js — Add a manual note to a recipient's profile.
 *
 * Strategy (fetch-then-patch):
 *   1. GET /api:bVXsw_FD/web/recipient?search=<phone> → find recipient and current note
 *   2. PATCH /api:bVXsw_FD/web/recipient/:id { note: <new_note> }
 *
 * Notes in Notifyer:
 *   - note      (manual note): Set by agents/scripts — visible in conversation view.
 *   - note_auto (AI note):     Auto-generated by AI summarisation — read-only via API.
 *
 * This script manages the MANUAL note field.
 * AI notes (note_auto) are written automatically by the AI and are read-only here.
 * Both notes can be read via: node scripts/get-notes.js
 *
 * Usage:
 *   node scripts/add-note.js --phone 14155550123 --note "VIP customer, prefers email"
 *   node scripts/add-note.js --phone 14155550123 --note "Follow up on 25 Jan" --pretty
 *   node scripts/add-note.js --phone 14155550123 --note "" --pretty  # clear note
 *   node scripts/add-note.js --phone 14155550123 --append "Added to loyalty program."
 *
 * Required Flags:
 *   --phone <number>    Recipient phone number WITHOUT + prefix (integer).
 *
 * Mutually exclusive note content flags (one required):
 *   --note <text>       Replace the entire note with this text. Use "" to clear.
 *   --append <text>     Append text to existing note (adds newline separator).
 *
 * Optional Flags:
 *   --pretty            Print before/after note content to stderr.
 *
 * Output (success):
 *   {
 *     "ok": true,
 *     "data": {
 *       "id": 42,
 *       "note": "VIP customer, prefers email",
 *       "note_auto": "...",
 *       "previous_note": "Old note text"
 *     }
 *   }
 *
 * CORS: Xano runs /cors_origin_web_chat on PATCH /web/recipient/:id.
 *   Script sends Origin: https://chat.notifyer-systems.com.
 *
 * Auth: Authorization: <token> (raw JWT, no Bearer — chat auth mode).
 *
 * Environment:
 *   NOTIFYER_API_BASE_URL    required
 *   NOTIFYER_API_TOKEN       required (from setup-notifyer/login.js)
 *   NOTIFYER_CHAT_ORIGIN     optional (default: https://chat.notifyer-systems.com)
 */

import { loadConfig, requestJson, AUTH_MODE_CHAT } from "./lib/notifyer-api.js";
import { parseArgs, getFlag, getBooleanFlag } from "./lib/args.js";
import { ok, err, printJson } from "./lib/result.js";

const CHAT_ORIGIN = process.env.NOTIFYER_CHAT_ORIGIN ?? "https://chat.notifyer-systems.com";

async function getUserId(config) {
  const result = await requestJson(config, {
    method: "GET",
    path: "/api:-4GSCDHb/auth/me",
  });
  if (!result.ok) return null;
  return result.data?.user_id ?? result.data?.id ?? null;
}

async function findRecipient(config, phone) {
  const parts = [
    `page_number=0`,
    `per_page=20`,
    `search=${encodeURIComponent(String(phone))}`,
    `labels=[]`,
    `status=`,
  ];
  const result = await requestJson(config, {
    method: "GET",
    path: `/api:bVXsw_FD/web/recipient?${parts.join("&")}`,
    extraHeaders: { Origin: CHAT_ORIGIN },
  });
  if (!result.ok) return result;
  const items = Array.isArray(result.data) ? result.data : [];
  const match = items.find((row) => {
    const r = (row.recipient && typeof row.recipient === "object") ? row.recipient : row;
    return String(r.phone_number) === String(phone) ||
      String(r.phone_number_string ?? "").replace(/\D/g, "") === String(phone).replace(/\D/g, "");
  });
  if (match) return { ok: true, data: (match.recipient && typeof match.recipient === "object") ? match.recipient : match };

  const userId = await getUserId(config);
  if (!userId) {
    return { ok: false, error: `Recipient with phone ${phone} not found (web search empty; could not resolve user for chatapp lookup).` };
  }
  const chatResult = await requestJson(config, {
    method: "GET",
    path: `/api:bVXsw_FD/chatapp/recipient?phone_number=${encodeURIComponent(String(phone))}&user_id=${userId}`,
  });
  if (!chatResult.ok) return { ok: false, error: `Recipient with phone ${phone} not found.` };
  const raw = Array.isArray(chatResult.data) ? chatResult.data[0] : chatResult.data;
  if (!raw || (Array.isArray(chatResult.data) && chatResult.data.length === 0)) {
    return { ok: false, error: `Recipient with phone ${phone} not found.` };
  }
  return { ok: true, data: raw };
}

async function main() {
  const flags = parseArgs();
  const phoneRaw = getFlag(flags, "phone");
  const noteRaw = getFlag(flags, "note");
  const appendRaw = getFlag(flags, "append");
  const pretty = getBooleanFlag(flags, "pretty");

  if (!phoneRaw) {
    printJson(err("--phone is required."));
    return;
  }
  if (noteRaw === undefined && appendRaw === undefined) {
    printJson(err("Either --note <text> or --append <text> is required."));
    return;
  }
  if (noteRaw !== undefined && appendRaw !== undefined) {
    printJson(err("Use either --note or --append, not both."));
    return;
  }

  const phone = phoneRaw.replace(/^\+/, "");

  const config = loadConfig({ authMode: AUTH_MODE_CHAT, requireToken: true });

  const findResult = await findRecipient(config, phone);
  if (!findResult.ok) {
    printJson(err(findResult.error, findResult.data, false, findResult.status));
    return;
  }

  const recipient = findResult.data;
  const existingNote = recipient.note ?? "";
  const existingNoteAuto = recipient.note_auto ?? "";

  let newNote;
  if (appendRaw !== undefined) {
    newNote = existingNote ? `${existingNote}\n${appendRaw}` : appendRaw;
  } else {
    newNote = noteRaw;
  }

  if (pretty) {
    process.stderr.write(`\nUpdating note for ${recipient.name ?? recipient.phone_number}\n`);
    process.stderr.write(`  Before: "${existingNote || "(empty)"}"\n`);
    process.stderr.write(`  After:  "${newNote || "(empty)"}"\n\n`);
  }

  const patchResult = await requestJson(config, {
    method: "PATCH",
    path: `/api:bVXsw_FD/web/recipient/${recipient.id}`,
    body: {
      name: recipient.name ?? "",
      phone_number: recipient.phone_number,
      phone_number_string: recipient.phone_number_string ?? String(recipient.phone_number ?? phone),
      global_label: Array.isArray(recipient.global_label) ? recipient.global_label : [],
      is_ai_assistant: typeof recipient.is_ai_assistant === "boolean" ? recipient.is_ai_assistant : false,
      note: newNote,
    },
    extraHeaders: { Origin: CHAT_ORIGIN },
  });

  if (!patchResult.ok) {
    printJson(err(patchResult.error, patchResult.data, false, patchResult.status));
    return;
  }

  printJson(ok({
    id: recipient.id,
    note: newNote,
    note_auto: existingNoteAuto,
    previous_note: existingNote,
  }));
}

main().catch((e) => { printJson(err(`Unexpected error: ${e.message}`)); });
