#!/usr/bin/env node
/**
 * get-notes.js — Get manual and AI-generated notes for a recipient.
 *
 * GET /api:bVXsw_FD/web/recipient?search=<phone>
 *
 * Reads both note types from the recipient record:
 *   - note      Manual note (written by agents via add-note.js)
 *   - note_auto AI-generated note (auto-created by AI summarisation)
 *
 * Usage:
 *   node scripts/get-notes.js --phone 14155550123
 *   node scripts/get-notes.js --phone 14155550123 --pretty
 *
 * Required Flags:
 *   --phone <number>    Recipient phone number WITHOUT + prefix (integer).
 *
 * Optional Flags:
 *   --pretty            Print notes in human-readable format to stderr.
 *
 * Output (success):
 *   {
 *     "ok": true,
 *     "data": {
 *       "id": 42,
 *       "name": "John Doe",
 *       "phone_number": 14155550123,
 *       "note": "VIP customer, prefers email follow-up.",
 *       "note_auto": "Customer asked about order #12345 status on Jan 25.",
 *       "has_manual_note": true,
 *       "has_ai_note": true
 *     }
 *   }
 *
 * Notes overview:
 *   note       Editable via add-note.js. Free-form text set by humans/agents.
 *              Displayed in the conversation sidebar in chat.notifyer.
 *   note_auto  Auto-generated by Notifyer's AI during conversation summarisation.
 *              Read-only from the API (set by Xano AI logic).
 *              Shows an AI-generated summary of conversation context.
 *
 * CORS: GET /web/recipient uses /cors_origin_web_chat.
 *   Script sends Origin: https://chat.notifyer-systems.com.
 *
 * Auth: Authorization: <token> (raw JWT, no Bearer — chat auth mode).
 *
 * Environment:
 *   NOTIFYER_API_BASE_URL    required
 *   NOTIFYER_API_TOKEN       required (from setup-notifyer/login.js)
 *   NOTIFYER_CHAT_ORIGIN     optional (default: https://chat.notifyer-systems.com)
 */

import { loadConfig, requestJson, AUTH_MODE_CHAT } from "./lib/notifyer-api.js";
import { parseArgs, getFlag, getBooleanFlag } from "./lib/args.js";
import { ok, err, printJson } from "./lib/result.js";

const CHAT_ORIGIN = process.env.NOTIFYER_CHAT_ORIGIN ?? "https://chat.notifyer-systems.com";

async function getUserId(config) {
  const result = await requestJson(config, { method: "GET", path: "/api:-4GSCDHb/auth/me" });
  if (!result.ok) return null;
  return result.data?.user_id ?? result.data?.id ?? null;
}

async function findRecipient(config, phone) {
  const parts = [
    `page_number=0`,
    `per_page=20`,
    `search=${encodeURIComponent(phone)}`,
    `labels=[]`,
    `status=`,
  ];
  const result = await requestJson(config, {
    method: "GET",
    path: `/api:bVXsw_FD/web/recipient?${parts.join("&")}`,
    extraHeaders: { Origin: CHAT_ORIGIN },
  });
  if (!result.ok) return result;
  const items = Array.isArray(result.data) ? result.data : [];
  const match = items.find((row) => {
    const r = (row.recipient && typeof row.recipient === "object") ? row.recipient : row;
    return String(r.phone_number) === String(phone) ||
      String(r.phone_number_string ?? "").replace(/\D/g, "") === String(phone).replace(/\D/g, "");
  });
  if (match) return { ok: true, data: (match.recipient && typeof match.recipient === "object") ? match.recipient : match };

  // Fallback: chatapp/recipient (doesn't carry note_auto, so after finding the ID
  // we re-fetch from web/recipient by ID to get the full record including note_auto).
  const userId = await getUserId(config);
  if (!userId) return { ok: false, error: `Recipient with phone ${phone} not found (web search empty; could not resolve user for chatapp lookup).` };
  const chatResult = await requestJson(config, {
    method: "GET",
    path: `/api:bVXsw_FD/chatapp/recipient?phone_number=${encodeURIComponent(phone)}&user_id=${userId}`,
  });
  if (!chatResult.ok) return { ok: false, error: `Recipient with phone ${phone} not found.` };
  const raw = Array.isArray(chatResult.data) ? chatResult.data[0] : chatResult.data;
  if (!raw || (Array.isArray(chatResult.data) && chatResult.data.length === 0)) {
    return { ok: false, error: `Recipient with phone ${phone} not found.` };
  }
  // Re-fetch via web endpoint by ID to get note_auto and other full-record fields.
  if (raw.id) {
    const webById = await requestJson(config, {
      method: "GET",
      path: `/api:bVXsw_FD/web/recipient?page_number=0&per_page=20&search=${encodeURIComponent(phone)}&labels=[]&status=`,
      extraHeaders: { Origin: CHAT_ORIGIN },
    });
    if (webById.ok) {
      const webItems = Array.isArray(webById.data) ? webById.data : [];
      const webMatch = webItems.find((row) => {
        const r2 = (row.recipient && typeof row.recipient === "object") ? row.recipient : row;
        return r2.id === raw.id;
      });
      if (webMatch) return { ok: true, data: (webMatch.recipient && typeof webMatch.recipient === "object") ? webMatch.recipient : webMatch };
    }
  }
  return { ok: true, data: raw };
}

async function main() {
  const flags = parseArgs();
  const phoneRaw = getFlag(flags, "phone");
  const pretty = getBooleanFlag(flags, "pretty");

  if (!phoneRaw) {
    printJson(err("--phone is required. Provide phone number without + prefix (e.g. 14155550123)."));
    return;
  }

  const phone = phoneRaw.replace(/^\+/, "");

  const config = loadConfig({ authMode: AUTH_MODE_CHAT, requireToken: true });

  const findResult = await findRecipient(config, phone);
  if (!findResult.ok) {
    printJson(err(findResult.error, findResult.data, false, findResult.status));
    return;
  }

  const r = findResult.data;
  const manualNote = r.note ?? "";
  const aiNote = r.note_auto ?? "";

  if (pretty) {
    process.stderr.write(`\nNotes for ${r.name ?? r.phone_number_string ?? r.phone_number}\n`);
    process.stderr.write(`${"─".repeat(60)}\n`);
    process.stderr.write(`Manual Note:\n`);
    process.stderr.write(manualNote ? `  ${manualNote}\n` : `  (none)\n`);
    process.stderr.write(`\nAI-Generated Note:\n`);
    process.stderr.write(aiNote ? `  ${aiNote}\n` : `  (none)\n`);
    process.stderr.write("\n");
  }

  printJson(ok({
    id: r.id,
    name: r.name ?? null,
    phone_number: r.phone_number,
    note: manualNote,
    note_auto: aiNote,
    has_manual_note: manualNote.length > 0,
    has_ai_note: aiNote.length > 0,
  }));
}

main().catch((e) => { printJson(err(`Unexpected error: ${e.message}`)); });
